"""Walk-forward check: for a range of past dates, reproduce exactly what the
saved next-day models would have predicted -- using only data available the
day before -- then compare to what actually happened. No hindsight involved:
predictions are generated by loading the already-trained model artifacts and
calling .predict() on the feature row as of the prior trading day.

Usage:
    python src/backtest_dates.py            # last 30 trading days (default)
    python src/backtest_dates.py 10         # last 10 trading days
    python src/backtest_dates.py 2026-09-09 2026-09-10   # specific dates
"""
import json
import sys
from pathlib import Path

import joblib
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from config import CLASSIFICATION_THRESHOLD, DATA_DIR, MODELS_DIR, REPORTS_DIR, TICKERS
from features import build_features, FEATURE_COLUMNS
from fetch_data import fetch_macro_all
from macro_features import align_macro_to_ticker, build_macro_features

DEFAULT_LOOKBACK_DAYS = 30


def backtest_ticker(name: str, target_dates: list[str] | None, lookback_days: int, macro_df: pd.DataFrame) -> pd.DataFrame:
    df = pd.read_csv(DATA_DIR / f"{name}.csv", index_col=0, parse_dates=True)
    feats = build_features(df)
    aligned = align_macro_to_ticker(macro_df, feats.index)
    feats = feats.join(aligned)

    with open(MODELS_DIR / f"{name}_features.json") as f:
        manifest = json.load(f)

    reg = joblib.load(MODELS_DIR / f"{name}_regressor.joblib")
    clf = joblib.load(MODELS_DIR / f"{name}_classifier.joblib")

    if target_dates is None:
        # last N trading days that actually have a prior day to predict from
        dates = feats.index[1:]
        dates = dates[-lookback_days:]
        dates = [d.strftime("%Y-%m-%d") for d in dates]
    else:
        dates = target_dates

    rows = []
    for target_date in dates:
        target_ts = pd.Timestamp(target_date)
        if target_ts not in feats.index:
            rows.append({"ticker": name, "date": target_date, "note": "no trading data for this date"})
            continue

        loc = feats.index.get_loc(target_ts)
        if loc == 0:
            rows.append({"ticker": name, "date": target_date, "note": "no prior day available"})
            continue
        prior_ts = feats.index[loc - 1]

        x_all = feats.loc[[prior_ts], FEATURE_COLUMNS]
        if x_all.isna().any(axis=None):
            rows.append({"ticker": name, "date": target_date, "note": "feature row incomplete (NaN)"})
            continue

        prior_close = float(feats.loc[prior_ts, "close"])
        actual_close = float(feats.loc[target_ts, "close"])
        actual_return = actual_close / prior_close - 1
        actual_direction = "UP" if actual_return > 0 else "DOWN"

        pred_return = float(reg.predict(x_all[manifest["regressor"]])[0])
        pred_close = prior_close * (1 + pred_return)
        pred_up_proba = float(clf.predict_proba(x_all[manifest["classifier"]])[0][1])
        pred_direction = "UP" if pred_up_proba > CLASSIFICATION_THRESHOLD else "DOWN"

        rows.append({
            "ticker": name,
            "date": target_date,
            "prior_close": prior_close,
            "predicted_close": pred_close,
            "actual_close": actual_close,
            "price_error": pred_close - actual_close,
            "price_error_pct": (pred_close - actual_close) / actual_close * 100,
            "predicted_direction": pred_direction,
            "actual_direction": actual_direction,
            "direction_correct": pred_direction == actual_direction,
        })
    return pd.DataFrame(rows)


def plot_ticker(name: str, df: pd.DataFrame):
    d = df.dropna(subset=["actual_close", "predicted_close"])
    if d.empty:
        return
    fig, ax = plt.subplots(figsize=(9, 4.5))
    ax.plot(d["date"], d["actual_close"], label="Actual close", color="#333333", marker="o", markersize=3)
    ax.plot(d["date"], d["predicted_close"], label="Predicted close (next-day model)", color="#d1495b", marker="o", markersize=3)
    ax.set_title(f"{name}: walk-forward backtest, last {len(d)} trading days")
    ax.set_ylabel("Price")
    ax.legend()
    fig.autofmt_xdate(rotation=45)
    fig.tight_layout()
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    out_path = REPORTS_DIR / f"{name}_backtest_recent.png"
    fig.savefig(out_path, dpi=130)
    plt.close(fig)
    print(f"  saved chart to {out_path}")


def main():
    args = sys.argv[1:]
    lookback_days = DEFAULT_LOOKBACK_DAYS
    target_dates = None
    if len(args) == 1 and args[0].isdigit():
        lookback_days = int(args[0])
    elif len(args) >= 1:
        target_dates = args

    macro_df = build_macro_features(fetch_macro_all())

    all_rows = []
    for name in TICKERS.values():
        tdf = backtest_ticker(name, target_dates, lookback_days, macro_df)
        all_rows.append(tdf)
        plot_ticker(name, tdf)

    result = pd.concat(all_rows, ignore_index=True)
    pd.set_option("display.float_format", lambda x: f"{x:,.3f}")
    pd.set_option("display.width", 160)
    print(result.to_string(index=False))

    scored = result.dropna(subset=["direction_correct"])
    print("\n--- Summary ---")
    overall = scored["direction_correct"].mean()
    print(f"Overall directional accuracy: {overall:.1%}  ({int(scored['direction_correct'].sum())}/{len(scored)})")
    for name, g in scored.groupby("ticker"):
        acc = g["direction_correct"].mean()
        mape = g["price_error_pct"].abs().mean()
        print(f"  {name:<6}: directional accuracy {acc:.1%} ({int(g['direction_correct'].sum())}/{len(g)}), "
              f"mean abs price error {mape:.2f}%")

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    out_path = REPORTS_DIR / "backtest_recent.csv"
    result.to_csv(out_path, index=False)
    print(f"\nSaved full results to {out_path}")
    return result


if __name__ == "__main__":
    main()
